# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Site Setup
title: "The Arab Republic of Egypt’s<br/>Bilateral Investment Treaties:<br/>A Complete Index"
tagline: "An exhaustive archive of the 113 publicly available of 116 Egyptian bilateral investment treaties (BITs), featuring verified texts and original PDFs."
description: "An exhaustive archive of the 113 publicly available of 116 Egyptian bilateral investment treaties (BITs), featuring verified texts and original PDFs."
url: "https://egyptianbits.com" # custom domain
baseurl: "" # no subdirectory

# Author
author:
  name: Aya Hamza
  url: https://github.com/ayahamza1

# Pagination
paginate: 5

# Optional Custom Vars
version: 2.1.0

# GitHub Repo
github:
  repo: https://github.com/ayahamza1/EgyptianBITs

# Plugins (used by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-paginate
